### PR TITLE
Leak fixes

### LINKED ISSUE #4: OBS completely crashes if the model is not found
This means you can't get to the settings to change the path to the correct one.

### PR DESCRIPTION
**Pull request by ali1234**
Fixes various use-after-free and `nullptr` dereferencing bugs that happen when the model file can't be found.

Fixes #4

### CODE REVIEW

**Comment by ali1234** [comment]
This isn't complete yet. There is still the problem with filter being used after freeing when the maskctx couldn't be initialized.

File: obs-backscrub.cpp [hunk 1]
```diff
@@ -120,7 +121,7 @@ static obs_properties_t *obs_backscrub_get_properties(void *state) {
 }
 static void obs_backscrub_update(void *state, obs_data_t *settings) {
     obs_backscrub_filter_t *filter = (obs_backscrub_filter_t *)state;
-    const char *model = _obs_backscrub_get_model(settings);
+    char *model = _obs_backscrub_get_model(settings);
     obs_printf(filter, "update: model: %s=>%s", filter->modelname, model);
     // here we change any filter settings (eg: model used, feathering edges, bilateral smoothing)
     if (strcmp(model, filter->modelname)) {
```
Comment (ali1234) [inline obs-backscrub.cpp]: Note that here the `filter->modelname` is being compared to the output of `get_model` - ie it isn't put through `get_path` first. This is actually a bug because `get_path` doesn't change absolute paths, but it does change relative paths. `filter->modelname` always contains the absolute path, because it is always set to the output of `get_path`. So if the setting string is a relative path, this `strcmp` will never match, even if the user didn't change it! Therefore merging the two functions into one actually stealth-fixes a harmless bug.

**Comment by ali1234** [comment]
This seems to be stable now under the various situations where a model file can be missing:

 - The module data directory is missing at start-up
 - The module data directory exists but is empty at start-up
 - The filename stored in the settings points to a model file that doesn't exist at start-up (inside and outside the module directory)
 - Switching from a working model to a broken one (ie select a non-default model when the default one is missing, and then restore defaults)
 - Switching to a working model path from any of the above states

OBS reports no memory leaks at exit.

**Comment by phlash** [comment]
Thanks - works for me, no reported leaks :smile:
